### PR TITLE
added further move_base parameters for the reconfigurations

### PR DESCRIPTION
**Pull request by NadiaHG**
This PR comes together with https://github.com/rosin-project/metacontrol_move_base_configurations/pull/1 and it is related to https://github.com/rosin-project/metacontrol_sim/pull/36#issuecomment-631605601

### CODE REVIEW

**Comment by marioney** [comment]
I know this is my fault, but we've updated the inflation radius values.  
Can you change the inflation radius parameters,  the new values are  `0.5, 0.65, 0.8`

https://docs.google.com/spreadsheets/d/12aB35Jj4qmarIq3OWHocATmnDfUa6ftp_j09W5twy1g/edit#gid=1491795427&range=F12

I guess this also affects https://github.com/rosin-project/metacontrol_move_base_configurations/pull/1

**Comment by NadiaHG** [comment]
updated the values and re-autogenerated for both repos:
https://github.com/rosin-project/metacontrol_move_base_configurations/pull/2
https://github.com/rosin-project/rosin-experiments/pull/10/commits/9a50eba314f6fa8f28812f8309f516db884c7ff3

**Review by chcorbato — COMMENTED** [review]
I think @marioney can review this better

**Review by marioney — APPROVED** [review]

**Comment by marioney** [comment]
I think this looks very good. 

@chcorbato  Please go ahead and merge this

**Pull request merged**
