### PR TITLE
add all the posible configuration combinations for move_base node

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by NadiaHG** [comment]
I have added the 27 configurations of parameters and a sh script to generate all of them automatically.

@chcorbato feel free to change the name of the file and the name of the system to a more adequate one for you https://github.com/ipa-nhg/rosin-experiments/blob/f61b98945dfc7b71924fb8f9d88127a66f25faac/rosin_experiment/move_base/combinations/create_config_combination_move_base.sh#L20-L21 
(remember that the name of the system will also be the name of the auto-generated launch file and the ROS package that contains it)

@marioney feel free to update the parameter values if needed https://github.com/ipa-nhg/rosin-experiments/blob/f61b98945dfc7b71924fb8f9d88127a66f25faac/rosin_experiment/move_base/combinations/create_config_combination_move_base.sh#L5-L7
https://github.com/ipa-nhg/rosin-experiments/blob/f61b98945dfc7b71924fb8f9d88127a66f25faac/rosin_experiment/move_base/combinations/create_config_combination_move_base.sh#L11-L13
https://github.com/ipa-nhg/rosin-experiments/blob/f61b98945dfc7b71924fb8f9d88127a66f25faac/rosin_experiment/move_base/combinations/create_config_combination_move_base.sh#L17-L19

@darkobozhinoski FYI

**Comment by chcorbato** [comment]
Nice work!!
Since this repo is becoming and integral part of our MODELS project, shall we move it to the ROSIN organization @ipa-nhg ? This way we can track this work with the rest of the work we are doing for the paper experiments.

**Comment by NadiaHG** [comment]
@chcorbato 
Sure, I will today merge all pending PRs, clean the repo and add the global rossystem file of the experiment and then we can transfer the repository. I am not sure if have the required rights, if not I will transfer the ownership to you.

**Comment by chcorbato** [comment]
> @chcorbato
> Sure, I will today merge all pending PRs, clean the repo and add the global rossystem file of the experiment and then we can transfer the repository. I am not sure if have the required rights, if not I will transfer the ownership to you.

Perfect! Go ahead as you propose (1st transfer ownership to me and then I transfer it to rosin)

**Comment by NadiaHG** [comment]
@chcorbato you are now the owner, you can transfer the repository and change the name if needed.

**Comment by NadiaHG** [comment]
btw this PR can be closed, superseded by https://github.com/ipa-nhg/rosin-experiments/commit/f2d7865bba677a024b185e091dd84427332e627a

**Pull request closed without merging**
