### PR TITLE
Move rossystem files to Ros packages

### PR DESCRIPTION
**Pull request by NadiaHG**
:exclamation: this PR contains https://github.com/rosin-project/rosin-experiments/pull/10

Related to the comment: https://github.com/rosin-project/mros1_reasoner/pull/34#issuecomment-632612653
Merge together with: https://github.com/rosin-project/metacontrol_move_base_configurations/pull/3

Tested on the ROS tooling and works without problems, for the ROS tooling doesn't matters the path of the files and now we have split the files created within the tooling (design time) and the files autogenerated (with the script of with the Xtend artifacts of the DSLs).

### CODE REVIEW

**Review by chcorbato — COMMENTED** [review]
Looks good

**Comment by hsd-dev** [comment]
Sorry I am a bit confused. Where can I find the files previously in https://github.com/rosin-project/rosin-experiments/tree/master/metacontrol_models_experiment/MoveBaseConfigurations

**Comment by chcorbato** [comment]
Here: https://github.com/rosin-project/metacontrol_move_base_configurations 😄

**Comment by hsd-dev** [comment]
I had already gotten a solution for the previous directory structure :smile:   
We don't know all the names of these configuration packages beforehand, do we? How can we do a `rospack.find` without the package names?

**Comment by hsd-dev** [comment]
@ipa-nhg could you please create a meta-package for these configuration packages? I am not sure how else would I find them.

**Comment by chcorbato** [comment]
> We don't know all the names of these configuration packages beforehand, do we? How can we do a `rospack.find` without the package names?

That is true, I was using rospack when they were all in one package 😆

**Comment by hsd-dev** [comment]
> That is true, I was using rospack when they were all in one package 

I would prefer the previous solution if you guys don't mind :). I am still able to extract the .rossystem files with GitHub API with the new structure.
```
https://api.github.com/repos/{owner}/{repo}/contents/{pkg_path}
```
But the number of requests are limited (even running the script twice gives a `rate limit exceeded` error), since the number of packages is a lot.

**Comment by chcorbato** [comment]
> We don't know all the names of these configuration packages beforehand, do we?

Actually, we do.

It is a nasty hack, but maybe you can just find one based on the name, e.g. `f1_v1_r1` is the first one, and from that path extract the rest assuming the have the same parent folder.

But I think your idea idea of the metapackage is the way to go, simply make `metacontrol_move_base_configurations` a ROS meta-package and find it with ospack

Could you do it?
http://wiki.ros.org/catkin/package.xml#Metapackages

**Review by chcorbato — COMMENTED** [review]
@ipa-nhg with this code you create a src-gen directory in src with the folder structure and .rossystem files, but how do you make all those folders ROS packages?

**Comment by NadiaHG** [comment]
> > We don't know all the names of these configuration packages beforehand, do we?
> 
> Actually, we do.
> 
> It is a nasty hack, but maybe you can just find one based on the name, e.g. `f1_v1_r1` is the first one, and from that path extract the rest assuming the have the same parent folder.
> 
> But I think your idea idea of the metapackage is the way to go, simply make `metacontrol_move_base_configurations` a ROS meta-package and find it with ospack
> 
> Could you do it?
> http://wiki.ros.org/catkin/package.xml#Metapackages

sorry for the delay, but you have a yaml file that is created together with all the rosystem files that hold the names of all the autogenerated configurations, solution that it is more consistent because everything autogenerated together https://github.com/rosin-project/rosin-experiments/pull/8 

this yaml file is loaded together with the rosgraph_manipulator https://github.com/rosin-project/metacontrol_sim/pull/36 and you can then get all the names of all the configuration with a  rosparam get https://github.com/rosin-project/metacontrol_sim/pull/36/files#diff-d3e0da30c311b74a6fc686d604bf3e42R119 

we can keep @ipa-hsd solution for now but I don't like the use of a metapackage created manually, then I suggest to modify the rossystem generator script to create it automatically... but I know... future work

**Comment by NadiaHG** [comment]
> @ipa-nhg with this code you create a src-gen directory in src with the folder structure and .rossystem files, but how do you make all those folders ROS packages?

this is part of the ROS tooling, if you import a rossystem file to the ROS tooling and it is valid the deployment artifacts are completely autogenerated. My DSL do it automatically for you. 


----


EDITED:
see: https://github.com/rosin-project/rosin-experiments/issues/12#issuecomment-633065902

**Comment by chcorbato** [comment]
Thanks for all these explanation @ipa-nhg 
It would be nice to have them in a README file or something, they are very valuable and these days I am having troubles finding these useful comments on Githuh 😄

**Comment by NadiaHG** [comment]
Yes, I wrote the instructions [here](https://github.com/rosin-project/rosin-experiments/tree/master/metacontrol_models_experiment#function-designs-models-for-move_base) when I created the repo but probably for the last two days a more extensive documentation was needed. I am sorry if I delayed you.

I will consolidate tomorrow all the readmes of my repos.

**Pull request merged**
